name: Xcode Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: latest-stable
        
    - name: Build and Test Xcode Project
      run: |
        xcodebuild -scheme SonarCloudPoC clean build test
